### ISSUE TITLE
Type signature for newtypes variant in externally-tagged enums do not align with what serde outputs

### ISSUE THREAD

**Issue by AlisCode** [impero-com/typebinder#21]
```rust
#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum A {
    AllDays,
    OneDay(B),
}

pub enum B {
    Monday,
    Tuesday,
}
```

TypeBinder generates a type signature that does not align with what serde outputs.

**Comment by AlisCode** [comment]
For the record, typebinder currently generates

```

export type A = ( {
	type: "AllDays"
} ) | ( {
	type: "OneDay"
} & B );

export type B = "Monday" | "Tuesday";
```

While `serde` outputs : 

```
println!("{}", serde_json::to_string(&A::AllDays).unwrap());
println!("{}", serde_json::to_string(&A::OneDay(B::Monday)).unwrap());
=> 
{"type":"AllDays"}
{"type":"OneDay","Monday":null}
```

**Comment by AlisCode** [comment]
I tried changing the definition of A for the sake of it : 

```
#[derive(Serialize)]
#[serde(tag = "type")]
pub enum A {
    AllDays,
    OneDay(u32),
}
``` 

And `OneDay(String)` as well, but both leads to runtime error. I'm really not sure what the correct behaviour is, here.

**Comment by gobanos** [comment]
If we want to generate bindings for the `{"type":"OneDay","Monday":null}` variant, we can use the following TS : 
```typescript
// RUNTIME
type FixEnum<T> = T extends string ? { [K in T]: null } : T;

// GENERATED
export type A = ( {
	type: "AllDays"
} ) | ( {
	type: "OneDay"
} & FixEnum<B> );

export type B = "Monday" | "Tuesday";
```
I haven't evaluated the cost of using utility types in typebinder yet.

NOTE: Using a generic is mandatory : `type FixB = B extends string ? { [K in B]: null } : B` differs from `FixEnum<B>`...

**Comment by AlisCode** [comment]
As we discussed, I don't really like having "runtime types" for the purpose of this project. This is just open-bar for more hacks. That being said : 
* This hack provides at least correct bindings for the failing case, that's good. But 
* I dont want to have us create/maintain an NPM package containing just a type hack, and it's not even clear it's the correct way forward
* Embedding a copy of the typebinder typesystem hack in generated files is also a terrible idea because the files aren't "pure" anymore, but I dont see an other way     
* The "best" solution is still very not clear to me here

It seems to me like this is a "corner case" error that originates from the `serde` design, and that the JSON that `serde_json` generates is virtually useless in this case. If the user has that pattern in their codebase, they won't be able to do much with it anyway since they'll be blocked by what `serde` has to offer, and they should change their codebase to use another serde representation that is JSON-compatible.

... I think if we don't want to start plaguing the project with countless hacks, we should just apply the `wont-fix` label to this issue and close it.

**Comment by gobanos** [comment]
> If the user has that pattern in their codebase, they won't be able to do much with it anyway since they'll be blocked by what serde has to offer, and they should change their codebase to use another serde representation that is JSON-compatible.
I agree with your analysis, but I think we should make it more explicit that this model is not supported.

I didn't managed to amplify the error in order to make the whole type unusable, but I think this will show the intent : 
```typescript
export type A = ( {
	type: "AllDays"
} ) | ( {
	type: "OneDay"
} & Extract<B, object> );

export type B = "Monday" | "Tuesday";
```
In this case the `"OneDay"` variant is infer to `never` so the resulting `A` is equivalent to `{ type: "AllDays" }`.

[link to TS playground with various cases](https://www.typescriptlang.org/play?ts=4.2.3#code/PTAEFUBUEkBkGUBQAzArgOwMYBcCWB7dUAQwGdSBTAJ2wDkKA3agCgA8AuUdR6gSlADeiAJCZCpfABsKAOmpV8VZgCIylGvSZVlvANyIAvokQhQAcQCitCwCUAgpAsARRNgCeABwqh42KqABeUGU7ZVAAH2CAIWV9dy9QAFlcVkDg0IjBUCjOdFQAWwAjalADOM9vAHlCgCs0gVA7XILi-wNMhpyuFpKy43iqj2xffyDmQREBzmVaQgplQ1B+SPGhYSng+Hx8+cWAMlALVj9iHAAeEYAaUHxaihwAPiX9VwrQSqHk1LGJ9Yrp2bcBbtZagVaTf6bba7doHI4nc5fa63Gr3bBPPTGUyOeCQJBoLB4QigUh+ZgMYiSTgfYZ+fhrUgAd1w2EwAAswRTJDIBvSRKIyN4ZnNlOx+aJxFJZJJ8ABzFSkqjsdAizHCdWFKgUYgAa306swgqhO1F4twyDBITCuCIXL56oNkukMhl8uUivYxB0+vV7QokkooHNlpiQdtlPtDrE6AkztdCr87EK3vFfoD3jWDrU1DoPCUdp9wiMDs12r1-IAJhRkMRUJJsGKs+Qc5oWAWREYjIhFcwGhthUDSpie33Icotibrk1upJJEP9CPQP2J-Nrl08rP592yaOvNMV8op81Z2vj3ODJiUBgcAQiPkUuTKdTPil7UyWezOZSeRVI4bAwO8yNo6MZSi6coqPeHAqkCaoalquo+v+QoHsBwjBioGQ2qAdq-FGTrShByhQZ6KYOmmgYYcoobYbhmYgbGhFuiRyZwUWoD+oG9HCNmGh5o+khscW8Flj6VY1nWDbirxuZaAJaqdsYUG9kuY6AvMW7KbuFD7tCh6NGemkPtpumTtknAAIxGawKnLnpR4zpIp6gAATFuV6EreNy1AJz7YNUNRvsyrIcgJP5eH+RqAaa+GgXGREosqqqFqWiH8shxpAWaFqYda4aCXhDFgfGyiJV6QkcemQY5dReU4RGhUSnFTEqIlrGFhRGbijxzZ8XJ7bkeKqXluq4m1vWaEya2+YRvqimICitlqSKW6LSZmX6dOADMq0+et472eZoAACy7TUS17htDkAKzOQAbPOQA)

**Comment by AlisCode** [comment]
Briliant. 

Let's say that we should just replace `& B` with `& Extract<B, object>`.

For the record, I wondered why we couldn't use `{}` in this case, so here is a SO post showing the difference between TS' `Object`, `object` and `{}` : https://stackoverflow.com/questions/49464634/difference-between-object-and-object-in-typescript

**Comment by AlisCode** [comment]
Fixed with this commit https://github.com/impero-com/typebinder/commit/d9cb450281bbb5ad141a20287c8a820a2be2000d

Did not implement the solution of `Extract<B, object>` as it felt weird to produce an unusable biding. 

I just removed the variants that would produce an invalid serde representation at runtime (that is internally-tagged enum with variants that are Newtypes or Tuples). We also now log a warning if the user had such case in their codebase. The best solution IMHO would probably be to generate a warning and stick it inside the generated code, but our AST doesn't support doing that, so let's forget it.

Closing this
